services:
  mc-wol-proxy:
    build: .
    restart: unless-stopped
    network_mode: host
    volumes:
      - ../config.yml:/config.yml:ro
      - ~/.ssh/id_ed25519:/root/.ssh/id_ed25519:ro
    environment:
      MC_WOL_CONFIG: /config.yml
